services:
  app:
    build: .
    container_name: hope-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/investment_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Kenzi2401
    ports:
      - "8080:8080"